//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace dv21 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CardDefinition {
        
        private ActionType[] actionsField;
        
        private CategoryType categoryField;
        
        private ModeType[] modesField;
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private SectionType[] sectionsField;
        
        private ViewElementType[] viewElementsField;
        
        private string idField;
        
        private string categoryIDField;
        
        private string aliasField;
        
        private string schemaField;
        
        private int versionField;
        
        private bool singleToneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Action", IsNullable=false)]
        public ActionType[] Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        public CategoryType Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Mode", IsNullable=false)]
        public ModeType[] Modes {
            get {
                return this.modesField;
            }
            set {
                this.modesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Section", IsNullable=false)]
        public SectionType[] Sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ViewElement", IsNullable=false)]
        public ViewElementType[] ViewElements {
            get {
                return this.viewElementsField;
            }
            set {
                this.viewElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool SingleTone {
            get {
                return this.singleToneField;
            }
            set {
                this.singleToneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActionType {
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LocalizedStringsLocalizedString {
        
        private string languageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewColumnType {
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private string aliasField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewElementType {
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private ViewColumnType[] columnsField;
        
        private string idField;
        
        private bool defaultField;
        
        private bool defaultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Column", IsNullable=false)]
        public ViewColumnType[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultSpecified {
            get {
                return this.defaultFieldSpecified;
            }
            set {
                this.defaultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FieldType {
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private FieldTypeEnum[] enumField;
        
        private string aliasField;
        
        private string idField;
        
        private FieldTypeType typeField;
        
        private int maxField;
        
        private bool maxFieldSpecified;
        
        private bool notNullField;
        
        private bool notNullFieldSpecified;
        
        private bool isBriefField;
        
        private bool isBriefFieldSpecified;
        
        private bool referenceField;
        
        private bool referenceFieldSpecified;
        
        private bool lookupField;
        
        private bool lookupFieldSpecified;
        
        private string refTypeField;
        
        private string refSectionField;
        
        private string lookupExpressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Enum")]
        public FieldTypeEnum[] Enum {
            get {
                return this.enumField;
            }
            set {
                this.enumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FieldTypeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxSpecified {
            get {
                return this.maxFieldSpecified;
            }
            set {
                this.maxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool NotNull {
            get {
                return this.notNullField;
            }
            set {
                this.notNullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotNullSpecified {
            get {
                return this.notNullFieldSpecified;
            }
            set {
                this.notNullFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsBrief {
            get {
                return this.isBriefField;
            }
            set {
                this.isBriefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBriefSpecified {
            get {
                return this.isBriefFieldSpecified;
            }
            set {
                this.isBriefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceSpecified {
            get {
                return this.referenceFieldSpecified;
            }
            set {
                this.referenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Lookup {
            get {
                return this.lookupField;
            }
            set {
                this.lookupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LookupSpecified {
            get {
                return this.lookupFieldSpecified;
            }
            set {
                this.lookupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefType {
            get {
                return this.refTypeField;
            }
            set {
                this.refTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefSection {
            get {
                return this.refSectionField;
            }
            set {
                this.refSectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LookupExpression {
            get {
                return this.lookupExpressionField;
            }
            set {
                this.lookupExpressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FieldTypeEnum {
        
        private string nameField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum FieldTypeType {
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        @bool,
        
        /// <remarks/>
        datetime,
        
        /// <remarks/>
        @enum,
        
        /// <remarks/>
        bitmask,
        
        /// <remarks/>
        uniqueid,
        
        /// <remarks/>
        userid,
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        unistring,
        
        /// <remarks/>
        fileid,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        refid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SectionType {
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private FieldType[] fieldField;
        
        private SectionType[] sectionField;
        
        private string aliasField;
        
        private bool addHistoryField;
        
        private bool addWhoInfoField;
        
        private SectionTypeType typeField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public FieldType[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Section")]
        public SectionType[] Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AddHistory {
            get {
                return this.addHistoryField;
            }
            set {
                this.addHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AddWhoInfo {
            get {
                return this.addWhoInfoField;
            }
            set {
                this.addWhoInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SectionTypeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SectionTypeType {
        
        /// <remarks/>
        @struct,
        
        /// <remarks/>
        coll,
        
        /// <remarks/>
        tree,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModeType {
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private ModeTypeRestrict[] restrictField;
        
        private string idField;
        
        private bool allowAllActionsField;
        
        private bool allowAllActionsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Restrict")]
        public ModeTypeRestrict[] Restrict {
            get {
                return this.restrictField;
            }
            set {
                this.restrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowAllActions {
            get {
                return this.allowAllActionsField;
            }
            set {
                this.allowAllActionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowAllActionsSpecified {
            get {
                return this.allowAllActionsFieldSpecified;
            }
            set {
                this.allowAllActionsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeTypeRestrict {
        
        private ModeTypeRestrictType typeField;
        
        private string idField;
        
        private bool allowRunField;
        
        private bool allowRunFieldSpecified;
        
        private bool allowCreateField;
        
        private bool allowCreateFieldSpecified;
        
        private bool allowUpdateField;
        
        private bool allowUpdateFieldSpecified;
        
        private bool allowDeleteField;
        
        private bool allowDeleteFieldSpecified;
        
        private bool allowReadField;
        
        private bool allowReadFieldSpecified;
        
        private bool allowWriteField;
        
        private bool allowWriteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModeTypeRestrictType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowRun {
            get {
                return this.allowRunField;
            }
            set {
                this.allowRunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowRunSpecified {
            get {
                return this.allowRunFieldSpecified;
            }
            set {
                this.allowRunFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowCreate {
            get {
                return this.allowCreateField;
            }
            set {
                this.allowCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowCreateSpecified {
            get {
                return this.allowCreateFieldSpecified;
            }
            set {
                this.allowCreateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowUpdate {
            get {
                return this.allowUpdateField;
            }
            set {
                this.allowUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowUpdateSpecified {
            get {
                return this.allowUpdateFieldSpecified;
            }
            set {
                this.allowUpdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowDelete {
            get {
                return this.allowDeleteField;
            }
            set {
                this.allowDeleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowDeleteSpecified {
            get {
                return this.allowDeleteFieldSpecified;
            }
            set {
                this.allowDeleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowRead {
            get {
                return this.allowReadField;
            }
            set {
                this.allowReadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowReadSpecified {
            get {
                return this.allowReadFieldSpecified;
            }
            set {
                this.allowReadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowWrite {
            get {
                return this.allowWriteField;
            }
            set {
                this.allowWriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowWriteSpecified {
            get {
                return this.allowWriteFieldSpecified;
            }
            set {
                this.allowWriteFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModeTypeRestrictType {
        
        /// <remarks/>
        action,
        
        /// <remarks/>
        section,
        
        /// <remarks/>
        field,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CategoryType {
        
        private LocalizedStringsLocalizedString[] nameField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable=false)]
        public LocalizedStringsLocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
