using System.Collections.Generic;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.209
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.209.
// 
namespace dv21 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("DefFile", Namespace="", IsNullable=false)]
    public class DefFile {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Paths")]
        public List<string> Paths { get; set; }
    }
}
