export enum InputTypeEnum {
  PLAINTEX_INPUT = 'PLAINTEX_INPUT',

  MULTILINE_INPUT = 'MULTILINE_INPUT',

  HTML_INPUT = 'HTML_INPUT',

  DATE_INPUT = 'DATE_INPUT',

  DATETIME_INPUT = 'DATETIME_INPUT',

  TIME_INPUT = 'TIME_INPUT',

  INTEGER_INPUT = 'INTEGER_INPUT',

  NUMBER_INPUT = 'NUMBER_INPUT',

  REFERENCE_INPUT = 'REFERENCE_INPUT',

  COMBOBOX_INPUT = 'COMBOBOX_INPUT',

  OPTION_INPUT = 'OPTION_INPUT',
}
