package com.bami.ef.tent.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigAllPropertiesEquals(RequestConfig expected, RequestConfig actual) {
        assertRequestConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigAllUpdatablePropertiesEquals(RequestConfig expected, RequestConfig actual) {
        assertRequestConfigUpdatableFieldsEquals(expected, actual);
        assertRequestConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigAutoGeneratedPropertiesEquals(RequestConfig expected, RequestConfig actual) {
        assertThat(expected)
            .as("Verify RequestConfig auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigUpdatableFieldsEquals(RequestConfig expected, RequestConfig actual) {
        assertThat(expected)
            .as("Verify RequestConfig relevant properties")
            .satisfies(e -> assertThat(e.getRequestType()).as("check requestType").isEqualTo(actual.getRequestType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigUpdatableRelationshipsEquals(RequestConfig expected, RequestConfig actual) {
        assertThat(expected)
            .as("Verify RequestConfig relationships")
            .satisfies(
                e -> assertThat(e.getRequestContentConfig()).as("check requestContentConfig").isEqualTo(actual.getRequestContentConfig())
            );
    }
}
