package com.bami.tent.request.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigAllPropertiesEquals(RequestConfig expected, RequestConfig actual) {
        assertRequestConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigAllUpdatablePropertiesEquals(RequestConfig expected, RequestConfig actual) {
        assertRequestConfigUpdatableFieldsEquals(expected, actual);
        assertRequestConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigAutoGeneratedPropertiesEquals(RequestConfig expected, RequestConfig actual) {
        assertThat(expected)
            .as("Verify RequestConfig auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigUpdatableFieldsEquals(RequestConfig expected, RequestConfig actual) {
        assertThat(expected)
            .as("Verify RequestConfig relevant properties")
            .satisfies(e -> assertThat(e.getVersion()).as("check version").isEqualTo(actual.getVersion()))
            .satisfies(e -> assertThat(e.getEffectiveDateStart()).as("check effectiveDateStart").isEqualTo(actual.getEffectiveDateStart()))
            .satisfies(e -> assertThat(e.getEffectiveDateEnd()).as("check effectiveDateEnd").isEqualTo(actual.getEffectiveDateEnd()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestConfigUpdatableRelationshipsEquals(RequestConfig expected, RequestConfig actual) {
        assertThat(expected)
            .as("Verify RequestConfig relationships")
            .satisfies(e -> assertThat(e.getRequestType()).as("check requestType").isEqualTo(actual.getRequestType()));
    }
}
