delete from mapper;
delete from dest_data;


insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','client_id','reference int8','Идентификатор клиента');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','inn','text','ИНН');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','kpp','text','КПП');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','ogrn','text','ОГРН');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','short_name','text','Короткое название');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','full_name','text','Полное название');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','main_email_address','text','Основной E-mail организации');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','main_phone_number','text','Основной телефон организации');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','okato','text','ОКАТО');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','registration_date','date','Дата регистрации ЮЛ');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','tax_registration_date','date','Дата постановки на налоговый учет');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','bik','text','БИК (только для клиентов-банков)');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','legal_form','text','Организационно-правовая форма');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','type','text','Тип клиента.');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','is_resident','boolean','Является ли юр. лицо резидентом РФ');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','created_ts','timestamptz','Время создания');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','modified_ts','timestamptz','Время изменения');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','created_by','text','Кем создано');
insert into dest_data(table_name,field_name,field_type, comment) values('client_detail','modified_by','text','Кем изменено');
insert into dest_data(table_name,field_name,field_type, comment) values('client','id','int8','Внутренний идентификатор клиента');
insert into dest_data(table_name,field_name,field_type, comment) values('client','crm_id','text','Идентификатор клиента во внешней мастер-системе');
insert into dest_data(table_name,field_name,field_type, comment) values('client','market_code','varchar(1)','Сегмент компании. Например: S,M,L');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','crm_address_id','text','Идентификатор записи (внешний)');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','client_id','reference int8','Идентификатор клиента');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','type','text','Тип адреса. Например: фактический/юридический');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','country','text','Страна');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','zip_code','text','Индекс');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','region','text','Регион');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','district','text','Район');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','city','text','Город');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','settlement','text','Населенный пункт');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','street','text','Улица');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','house','text','Дом');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','housing','text','Корпус');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','building','text','Строение');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','apartment','text','Квартира/комната');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','created_ts','timestamptz','Время создания');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','modified_ts','timestamptz','Время изменения');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','created_by','text','Кем создано');
insert into dest_data(table_name,field_name,field_type, comment) values('client_address','modified_by','text','Кем изменено');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','code','text','Уникальный код воркфлоу');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','object_type','text','Тип объектов,');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','initial_business_state','text','Начальный бизнес-статус объекта');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','final_business_state','text','Финальный бизнес-статус объекта');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','description','text','Поясняющее описание');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','is_active','boolean','Признак активности воркфлоу');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','created_ts','timestamptz','Дата и время добавления записи');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','modified_ts','timestamptz','Дата и время последнего изменения записи');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','created_by','text','Пользователь, добавивший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow','modified_by','text','Пользователь, изменивший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','workflow_code','reference text','Код ворфлоу');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','task_code','reference text','Код задания для выполнения');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','sort_order','integer','Задает порядок выполнения заданий.');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','description','text','Описание, комменты (при необходимости)');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','is_active','boolean','Признак активности задания.');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','created_ts','timestamptz','Дата и время создания записи');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','modified_ts','timestamptz','Дата и время последнего изменения записи');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','created_by','text','Пользователь, создавший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('workflow_task','modified_by','text','Пользователь, последний изменивший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('task','code','text','Уникальный код задания');
insert into dest_data(table_name,field_name,field_type, comment) values('task','description','text','Описание задания');
insert into dest_data(table_name,field_name,field_type, comment) values('process','id','int8','Уникальный ID процесса');
insert into dest_data(table_name,field_name,field_type, comment) values('process','object_id','int8','ID объекта, для которого запущен процесс');
insert into dest_data(table_name,field_name,field_type, comment) values('process','object_type','text','Тип объекта, для которого запущен процесс');
insert into dest_data(table_name,field_name,field_type, comment) values('process','workflow_code','reference text','Код воркфлоу, по которому запущен процесс');
insert into dest_data(table_name,field_name,field_type, comment) values('process','process_state','integer','Состояние процесса');
insert into dest_data(table_name,field_name,field_type, comment) values('process','business_date','date','Бизнес дата, на которую запущен процесс');
insert into dest_data(table_name,field_name,field_type, comment) values('process','external_btx_id','text','Идентификатор внешней транзакции');
insert into dest_data(table_name,field_name,field_type, comment) values('process','result_code','text','Код результата (ошибки).');
insert into dest_data(table_name,field_name,field_type, comment) values('process','result_message','text','Текст результата (ошибки).');
insert into dest_data(table_name,field_name,field_type, comment) values('process','created_ts','timestamptz','Дата и время добавления записи');
insert into dest_data(table_name,field_name,field_type, comment) values('process','modified_ts','timestamptz','Дата и время последнего изменения записи');
insert into dest_data(table_name,field_name,field_type, comment) values('process','created_by','text','Пользователь, добавивший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('process','modified_by','text','Пользователь, изменивший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','id','int8','Уникальный ID задания');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','process_id','reference int8','ID процесса');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','task_code','reference text','Код задания');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','task_state','integer','Состояние задания');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','result_code','text','Код результата (ошибки).');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','result_message','text','Текст результата (ошибки).');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','created_ts','timestamptz','Дата и время добавления записи');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','modified_ts','timestamptz','Дата и время последнего изменения записи');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','created_by','text','Пользователь, добавивший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task','modified_by','text','Пользователь, изменивший запись');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task_event','process_task_id','reference int8','ID выполняющегося задания,');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task_event','event_id','reference int8','ID события, подлежащего отправке');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task_event','created_ts','timestamptz','Время добавления записи в таблицу');
insert into dest_data(table_name,field_name,field_type, comment) values('process_task_event','created_by','text','Кем добавлена запись в таблицу');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','id','int8','Уникальный идентификатор записи');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','loan_id','reference int8','Внутренний уникальный идентификатор кредитного дог');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','debt_period_max_day','integer','Максимальный срок непрерывной задолженности по основному долгу.');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','overlimit_repayment_period_day','integer','Количество дней для погашения перелимита (рабочие ');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','usage_period_day','integer','Период использования овердрафта.');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','repayment_period_day','integer','Период погашения овердрафта.');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','limit_status','text','Статус  лимита.');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','is_interest_repayment','boolean','Признак погашения процентов по овердрафту,');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','is_effective','boolean','Флаг актуальности записи');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','effective_begin_date','date','Дата начала действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','effective_end_date','date','Дата окончания действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','process_id','int8','Идентификатор процесса (workflow),');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','created_ts','timestamptz','Когда создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','modified_ts','timestamptz','Когда изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('overdraft','modified_by','text','Кем изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','id','int8','Уникальный идентификатор записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','loan_id','reference int8','Внутренний уникальный идентификатор кредитного дог');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','loan_limit_type','integer','Тип лимита');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','renewable_limit_start_amount','numeric(18,8)','Первоначальная сумма возобновляемого лимита (лимита задолженности).');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','not_renewable_limit_start_amount','numeric(18,8)','Первоначальная сумма невозобновляемого лимита (лимита выдачи).');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','limit_availability_max_date','date','Максимальная дата доступности средств.');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','period_type','integer','Тип периода  максимального срока транша');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','period_count','integer','Количество периодов максимального срока транша');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','max_tranche_amount','numeric(18,8)','Максимальная сумма транша.');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','grace_period_begin_date','date','Дата начала отсрочки для погашения основного долга');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','grace_period_end_date','date','Дата окончания отсрочки для погашения основного до');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','is_effective','boolean','Флаг актуальности записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','effective_begin_date','date','Дата начала действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','effective_end_date','date','Дата окончания действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','process_id','int8','Идентификатор процесса (workflow),');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','created_ts','timestamptz','Когда создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','modified_ts','timestamptz','Когда изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent','modified_by','text','Кем изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan','id','int8','Внутренний уникальный идентификатор договора');
insert into dest_data(table_name,field_name,field_type, comment) values('loan','loan_agreement_number','text','Внешний межсистемный идентификатор договора.');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','id','int8','Уникальный идентификатор записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','loan_id','reference int8','Внутренний уникальный идентификатор договора');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','loan_number','text','Номер договора');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','begin_date','date','Дата начала договора');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','signing_date','date','Дата подписания договора');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','end_date','date','Дата завершения договора без переноса');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','end_date_with_shift','date','Дата завершения договора с переносом');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','actual_end_date','date','Фактическая дата завершения договора');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','amount','numeric(18,8)','Сумма договора (в мажорных единицах валюты)');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','currency_code','reference string','Валюта договора (основная)');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','parent_loan_id','int8','Внутренний уникальный идентификатор договора верхн');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','duration_days','integer','Срок договора (дни)');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','weekend_shift_type','integer','Тип сдвига даты окончания сделки с выходного дня');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','loan_product_code','reference text','Код кредитного продукта');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','calendar_code','reference text','Код календаря, применяемого к сделке');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','is_effective','boolean','Флаг актуальности записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','effective_begin_date','date','Дата начала действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','effective_end_date','date','Дата окончания действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','process_id','int8','Идентификатор процесса (workflow),');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','created_ts','timestamptz','Когда создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','modified_ts','timestamptz','Когда изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_detail','modified_by','text','Кем изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_product','code','text','Код кредитного продукта');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_product','name','text','Наименование кредитного продукта');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_product','type','integer','Тип кредитного продукта');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_product','description','text','Описание кредитного продукта');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_product','is_active','boolean','Активность кредитного продукта');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','id','int8','Уникальный идентификатор записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','loan_id','reference int8','Внутренний уникальный идентификатор кредитного дог');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','currency_code','reference string','Код валюты');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','is_effective','boolean','Флаг актуальности записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','effective_begin_date','date','Дата начала действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','effective_end_date','date','Дата окончания действия записи');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','process_id','int8','Идентификатор процесса (workflow),');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','created_ts','timestamptz','Когда создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','modified_ts','timestamptz','Когда изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('loan_parent_currency','modified_by','text','Кем изменена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('application_type','code','text','Код');
insert into dest_data(table_name,field_name,field_type, comment) values('application_type','name','text','Название');
insert into dest_data(table_name,field_name,field_type, comment) values('application','id','int8','Идентификатор');
insert into dest_data(table_name,field_name,field_type, comment) values('application','application_date','date','Дата заявки');
insert into dest_data(table_name,field_name,field_type, comment) values('application','loan_agreement_number','text','Номер договора');
insert into dest_data(table_name,field_name,field_type, comment) values('application','status','text','Текущий статус заявки');
insert into dest_data(table_name,field_name,field_type, comment) values('application','application_type_code','reference text','Тип заявки');
insert into dest_data(table_name,field_name,field_type, comment) values('application','source_system','text','Система источник');
insert into dest_data(table_name,field_name,field_type, comment) values('application','external_application_id','text','Идентификатор заявки во внешней системе');
insert into dest_data(table_name,field_name,field_type, comment) values('application','transport_id','text','Транспортный идентификатор');
insert into dest_data(table_name,field_name,field_type, comment) values('application','external_btx_id','text','Внешний идентификатор бизнес транзакции');
insert into dest_data(table_name,field_name,field_type, comment) values('application','payload','jsonb','Данные заявки');
insert into dest_data(table_name,field_name,field_type, comment) values('application','created_ts','timestamptz','Время создания');
insert into dest_data(table_name,field_name,field_type, comment) values('application','modified_ts','timestamptz','Время изменения');
insert into dest_data(table_name,field_name,field_type, comment) values('application','created_by','text','Кем создано');
insert into dest_data(table_name,field_name,field_type, comment) values('application','modified_by','text','Кем изменено');
insert into dest_data(table_name,field_name,field_type, comment) values('market_indicator','code','text','Рыночный код индикатора');
insert into dest_data(table_name,field_name,field_type, comment) values('market_indicator','type','text','Тип индикатора');
insert into dest_data(table_name,field_name,field_type, comment) values('market_indicator','name','text','Наименование индикатора');
insert into dest_data(table_name,field_name,field_type, comment) values('market_indicator','period_type','text','Периодичность индикатора');
insert into dest_data(table_name,field_name,field_type, comment) values('market_indicator','is_active','boolean','Флаг активности валюты (отключение валюты при необ');
insert into dest_data(table_name,field_name,field_type, comment) values('market_trade','market_indicator_code','reference text','Рыночный код индикатора');
insert into dest_data(table_name,field_name,field_type, comment) values('market_trade','start_date','date','Дата начала действия курса');
insert into dest_data(table_name,field_name,field_type, comment) values('market_trade','rate','numeric(18,8)','Значение ставки');
insert into dest_data(table_name,field_name,field_type, comment) values('market_trade','created_ts','timestamptz','Когда создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('market_trade','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('currency','code','varchar(3)','Алфавитный код валюты в стандарте ISO');
insert into dest_data(table_name,field_name,field_type, comment) values('currency','number_code','varchar(3)','Цифровой код валюты в стандарте ISO');
insert into dest_data(table_name,field_name,field_type, comment) values('currency','scale','integer','Количество минорных единиц валюты в 1 мажорной еди');
insert into dest_data(table_name,field_name,field_type, comment) values('currency','name','text','Наименование валюты');
insert into dest_data(table_name,field_name,field_type, comment) values('currency','is_active','boolean','Флаг активности валюты (отключение валюты при необ');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate','start_date','date','Дата начала действия курса');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate','buy_currency_code','reference string','Валюта покупки банком');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate','sell_currency_code','reference string','Валюта продажи банком');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate','rate_type','text','Тип обменного курса.');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate','rate','numeric(18,8)','Значение курса');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate','created_ts','timestamptz','Когда создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','id','int8','Уникальный идентификатор записи в журнале');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','start_date','date','Дата начала действия курса');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','buy_currency_code','reference string','Валюта покупки банком');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','sell_currency_code','reference string','Валюта продажи банком');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','rate_type','text','Тип обменного курса.');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','rate','numeric(18,8)','Значение курса');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','created_ts','timestamptz','Когда создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','transferred_ts','timestamptz','Когда перенесена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('currency_rate_history','transferred_by','text','Кем перенесена запись');
insert into dest_data(table_name,field_name,field_type, comment) values('event','id','int8','Идентификатор события');
insert into dest_data(table_name,field_name,field_type, comment) values('event','guid','UUID','UUID события');
insert into dest_data(table_name,field_name,field_type, comment) values('event','event_type','text','Тип события');
insert into dest_data(table_name,field_name,field_type, comment) values('event','is_new','boolean','Флаг нового события');
insert into dest_data(table_name,field_name,field_type, comment) values('event','is_sent','boolean','Флаг, что событие отправлено');
insert into dest_data(table_name,field_name,field_type, comment) values('event','created_ts','timestamptz','Дата и время создания события');
insert into dest_data(table_name,field_name,field_type, comment) values('event','modified_ts','timestamptz','Дата и время обновления события');
insert into dest_data(table_name,field_name,field_type, comment) values('event','created_by','text','Пользователь, создавший событие');
insert into dest_data(table_name,field_name,field_type, comment) values('event','modified_by','text','Пользователь, обновивший событие');
insert into dest_data(table_name,field_name,field_type, comment) values('event_attributes','event_id','reference int8','Идентификатор события');
insert into dest_data(table_name,field_name,field_type, comment) values('event_attributes','object_type','text','Тип объекта, связанного с событием');
insert into dest_data(table_name,field_name,field_type, comment) values('event_attributes','object_id','int8','Идентификатор объекта, связанного с событием');
insert into dest_data(table_name,field_name,field_type, comment) values('event_attributes','attributes','jsonb','Объект JSON с дополнительными атрибутами события');
insert into dest_data(table_name,field_name,field_type, comment) values('event_attributes','external_btx_id','text','Внешний идентификатор бизнес транзакции');
insert into dest_data(table_name,field_name,field_type, comment) values('event_attributes','operation_date','date','Бизнес дата события (не может быть выходным днем)');
insert into dest_data(table_name,field_name,field_type, comment) values('event_result','event_id','reference int8','Идентификатор события');
insert into dest_data(table_name,field_name,field_type, comment) values('event_result','result_code','integer','Код результата обработки события');
insert into dest_data(table_name,field_name,field_type, comment) values('event_result','result_message','text','Текст результата обработки события');
insert into dest_data(table_name,field_name,field_type, comment) values('event_result','error_code','text','Код ошибки,');
insert into dest_data(table_name,field_name,field_type, comment) values('event_result','created_ts','timestamptz','Дата и время добавления результата обработки событ');
insert into dest_data(table_name,field_name,field_type, comment) values('event_result','created_by','text','Пользователь,');
insert into dest_data(table_name,field_name,field_type, comment) values('lookup','lookup_type','text','Тип классификатора');
insert into dest_data(table_name,field_name,field_type, comment) values('lookup','lookup_code','text','Код в классификаторе.');
insert into dest_data(table_name,field_name,field_type, comment) values('lookup','description','text','Описание кода в классификаторе');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar','code','text','Код календаря');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar','is_default','boolean','Признак дефолтного календаря (использующегося по у');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar','is_active','boolean','Флаг активности календаря (при необходимости можно');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar','name','text','Наименование календаря');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar_date','calendar_code','reference text','Уникальный идентификатор производственного календа');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar_date','calendar_date','date','Календарная дата');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar_date','day_type','integer','Тип календарного дня');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar_date','created_by','text','Кем создана запись');
insert into dest_data(table_name,field_name,field_type, comment) values('calendar_date','created_ts','timestamptz','Когда создана запись');


 

